name: Deploy

on:
  push:
    branches:
      - master
      - buildx

jobs:
  build:
    strategy:
      matrix:
        image:
          # - name: latest
          #   python_version: "3.8"
          - name: python3.8
            python_version: "3.8"
          - name: python3.7
            python_version: "3.7"
          - name: python3.6
            python_version: "3.6"
          - name: python2.7
            python_version: "2.7"
          - name: python3.8-alpine
            python_version: "3.8"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        env:
          NAME: ${{ matrix.image.name }}
          DOCKERFILE: ${{ matrix.image.name }}.dockerfile
          PYTHON_VERSION: ${{ matrix.image.python_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker-images
          file: docker-images/${{ matrix.image.name }}.dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: guysoft/uwsgi-nginx-flask:${{ matrix.image.name }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}
